import { ShellLayout } from '@/components/layouts/shell'
import { Stack } from '@wonderflow/react-components'
import React from 'react'

export const Home = () => {
  return (
    <ShellLayout header={<div style={{ background: 'gray', height: 400 }}>COVER VIDEO</div>}>
      <Stack>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus natus error ab fugit nisi, quisquam, vero consectetur et, itaque magnam quaerat iusto eum. Vero eveniet doloribus quos, et modi doloremque.
        Numquam corrupti aperiam velit a eius laboriosam nisi provident dolorum ipsam, nulla nobis suscipit ut pariatur magni modi, totam quasi? Velit ad magni sequi itaque dolores dolorum? Ullam, nostrum iure.
        Voluptate, aliquam autem? Voluptatibus aliquid doloremque magni laudantium consequatur necessitatibus obcaecati eligendi! Eveniet et totam eius corporis amet quibusdam suscipit, illum consequuntur harum a distinctio, inventore velit possimus nam? Dolorum.
        Labore illo, quidem alias ipsam, quaerat maxime natus deserunt sit ab numquam nemo rem fugit excepturi! Voluptate id facilis nostrum, fuga ipsum similique nesciunt vero nemo provident quia ex explicabo.
        Mollitia consectetur maiores similique assumenda id sapiente iste amet quod modi. Voluptas illum quidem, sed dignissimos commodi consequuntur asperiores officia assumenda aperiam ullam eius error ea repellat beatae perferendis delectus.
        Reprehenderit atque porro rem quod! Ratione earum libero laboriosam sit numquam vel atque consectetur repudiandae voluptatibus cum sequi commodi quas eos nobis dolorum error ipsam, quo neque hic nam? Maxime.
        A quo at dolor, tempora laborum nostrum atque cum consectetur harum doloremque, corrupti ullam illum. Et laborum repellat ex, aliquam rerum deleniti nemo hic sed veritatis aspernatur asperiores distinctio? Unde.
        Vero, voluptate veniam asperiores necessitatibus sit alias eius autem, repudiandae ratione eaque, recusandae numquam quaerat impedit officia nostrum sunt! Ea inventore libero, aliquid ipsam nisi quia voluptates dolorum qui! Ut?
        Aperiam eveniet molestiae animi dolore, harum tempore fuga vero officia. Dolor, incidunt et eligendi velit minima voluptatum illo facilis atque ex earum in officia eius voluptatibus quo nemo quis aliquid.
        Hic numquam libero illo tenetur aut voluptate in ipsam autem? Consequuntur suscipit ipsum cupiditate recusandae! Mollitia, deserunt rem dolor veniam sequi iure rerum magni, doloribus odio fugiat quam tempora provident?
        Blanditiis reprehenderit quod obcaecati molestiae cumque molestias voluptatibus distinctio, deserunt laboriosam velit iure fugit quae vel perspiciatis adipisci ad temporibus. Error quam distinctio assumenda, nihil dolor mollitia expedita delectus sint.
        Maxime ipsa nesciunt veniam minus numquam nostrum quam. Qui consequuntur fugiat laborum velit! Aspernatur, debitis fugiat tenetur omnis distinctio quisquam pariatur odit officia eos nihil possimus aperiam, explicabo doloribus numquam!
        Facilis necessitatibus optio nulla accusamus? Laborum eius, blanditiis optio quae modi tempora eligendi fuga natus veniam veritatis eos at consequuntur harum a iure animi reiciendis est? Error vitae suscipit ducimus!
        Numquam at libero soluta vitae nostrum. In aliquid earum recusandae quo iste fugit explicabo doloremque tenetur dolor enim, provident assumenda ipsum natus consequatur, totam laborum ad quam amet quas! Nemo?
        Consequatur omnis commodi aspernatur, quaerat, necessitatibus error enim eveniet laborum tempora beatae impedit eligendi adipisci vitae in et excepturi illo molestiae odio quod nisi iste vero laudantium corrupti. Maxime, sapiente.
        Libero modi labore hic sapiente ratione quis mollitia perferendis ex, fuga id magni debitis similique molestias ducimus possimus dignissimos eius neque dicta voluptatum laboriosam maiores soluta tempora odit. Earum, sit?
        Nemo corrupti pariatur vitae et placeat. Cumque iusto perferendis, dolorum dignissimos molestiae atque aliquam asperiores fugit recusandae provident pariatur doloremque consequuntur optio, qui aperiam? Asperiores doloremque expedita provident magnam quisquam?
        Vero, nihil placeat quis molestias ad maxime fuga commodi eveniet, dolor necessitatibus ducimus consequuntur sequi quam corporis ex sint laboriosam harum distinctio alias earum natus neque minus tempora? Minima, illo.
        Cum corrupti est quod quas corporis soluta assumenda consectetur eos tenetur perferendis? In, aspernatur alias nostrum enim provident labore ipsam culpa temporibus voluptatum ipsa tempore eligendi unde laboriosam maiores iusto?
        Quisquam quidem quis dolores maxime sapiente excepturi modi, pariatur quasi deleniti deserunt aspernatur ducimus sed maiores similique nulla consectetur eligendi sit numquam voluptatibus. Nemo numquam earum aut eum consequatur magnam.
        Tempore, eligendi maiores vero nisi provident blanditiis corporis suscipit perspiciatis, temporibus excepturi facere sit? Iusto maxime quos eius facilis cupiditate excepturi deleniti rerum assumenda veniam, laboriosam provident doloribus repellat praesentium?
        Quos harum illum, cupiditate corporis illo adipisci, quisquam autem odit quis numquam obcaecati? Veniam consectetur at odit ipsam. Minima, eos officia odio atque magni rerum tempora dolorem et rem facilis.
        Quibusdam repellat blanditiis, odit voluptatibus doloremque nulla corporis sint accusantium eum aut laudantium error aliquam voluptate animi est officiis necessitatibus ducimus asperiores praesentium, dolore molestias accusamus. Minus id blanditiis temporibus?
        Quasi, consequuntur cupiditate fuga voluptatem repellendus optio sequi vel quod eius, natus cum impedit alias fugit autem necessitatibus, voluptatum tenetur et cumque illo praesentium! Accusantium velit maxime necessitatibus distinctio nesciunt.
        Voluptas iure esse molestias ut consequatur eveniet, omnis dignissimos suscipit optio nobis. Adipisci tempore consequuntur ipsam non iusto ipsa eligendi hic autem numquam sunt similique cupiditate voluptas, maiores ut dolore.
        Impedit perspiciatis ullam consequuntur eos eius, qui ab, recusandae unde suscipit cumque dolorum distinctio fugit totam quibusdam! Dolor inventore, possimus provident voluptatum officia temporibus quasi aliquam ex blanditiis similique eligendi!
        Nemo iure laboriosam temporibus hic perspiciatis numquam nisi enim illo dignissimos est, commodi qui consectetur quidem nostrum rerum nam impedit rem in deleniti aliquam itaque necessitatibus dolorum? Non, aspernatur culpa.
        Ducimus facere saepe eligendi minima, nisi quam itaque quas, harum, ullam quis illum consequuntur quasi est inventore voluptas doloribus. Officia consequuntur nemo voluptatibus eveniet illum explicabo aliquam iste veniam maiores.
        Optio inventore explicabo, natus pariatur non ratione, hic et similique libero doloribus suscipit reiciendis, neque error aliquam illum dolor? Distinctio ullam cumque accusantium hic laborum commodi quos aperiam. Quis, ipsam.
        Temporibus assumenda alias cum iusto debitis consequatur, nostrum vero, aliquid laborum eius et! Quis minima atque consequuntur, deleniti maxime pariatur earum quo voluptatem rem ipsa. Aliquid repellendus magni provident! Officiis?
        Accusamus sint autem aliquid quod ratione incidunt, dolorem corrupti ea, in provident enim? Doloribus eius enim porro ex officia, nisi earum maiores sequi, laborum illum ipsa asperiores quam quas ab.
        Recusandae harum illum dolorum nisi accusamus ratione fuga, est quam officiis, et reiciendis! Voluptatibus accusantium, debitis tenetur reiciendis reprehenderit perspiciatis neque quasi sit ducimus quia, id laudantium cum similique ratione.
        Vero, suscipit dicta obcaecati odio laboriosam, aliquid necessitatibus minima repudiandae ipsam rerum vel, atque quo eum architecto dolore veniam distinctio nam recusandae eius minus. Tenetur quo natus aspernatur omnis deleniti.
        Beatae laborum eveniet iusto neque impedit eum error, nisi non fugit sit ipsum alias repudiandae quia minima harum facilis quod temporibus eligendi cupiditate. Dolores voluptatibus sunt sit. Atque, odio. Fugiat.
        Expedita molestiae laboriosam esse veritatis optio similique dignissimos! Cumque nihil suscipit incidunt eum hic ipsum at ullam vel et dolore, vero, ad reiciendis, voluptatibus cupiditate minima quisquam dignissimos magni. Repudiandae?
        Dignissimos distinctio at dolorum repudiandae architecto, ducimus odio? Deserunt, non perferendis! Earum ratione natus aspernatur quas culpa, ducimus minus at perspiciatis vel accusantium placeat, enim magnam quos? Quae, rem ab?
        Iure, illum assumenda saepe possimus sed libero eos ad est facere voluptatem minima quibusdam, exercitationem vitae. Quisquam iusto soluta, non voluptatem molestias facilis dolores eaque illo earum hic aperiam consectetur?
        Ducimus suscipit, consequuntur, officia obcaecati aspernatur recusandae explicabo libero repellat ad maiores eum tenetur exercitationem. Molestiae tempore, doloremque, distinctio earum id itaque alias aspernatur pariatur, dolor dolores esse! Saepe, nam?
        Accusantium expedita, iure id eius quisquam autem atque incidunt consequuntur reiciendis suscipit veniam, maiores nemo commodi aperiam, ratione corrupti? Dolore amet natus laudantium, vel dolores enim excepturi expedita sed exercitationem?
        Aliquam accusantium enim nostrum labore iure nihil harum et eum quaerat consectetur deleniti molestiae officia earum, quibusdam natus quos? Nam corrupti cupiditate qui enim, dolorem dolore exercitationem nesciunt error et?
        Obcaecati sunt odit doloribus voluptates totam mollitia cupiditate laborum inventore rem magnam? Reiciendis quibusdam soluta nisi, deleniti fugit, atque laboriosam minima nam doloribus fuga facere error, natus id cumque officiis.
        Nobis repellendus est sunt iste fugit. Dignissimos nesciunt accusamus eius dolorum consequuntur atque reiciendis architecto exercitationem quam temporibus! Nemo, reiciendis eius esse perspiciatis cupiditate provident at ipsa dignissimos! Saepe, incidunt.
        Nobis earum vero, vitae ab dignissimos inventore voluptatibus minima iure nihil soluta repellat magnam quisquam fuga mollitia nesciunt eveniet numquam dicta ullam odio quia officiis. Veniam, asperiores? Labore, magni eius?
        Minus, nostrum debitis sapiente fugiat aperiam consequatur? Iure incidunt consequuntur non eos. Facilis neque reprehenderit libero totam eius repellat odio non, quos accusantium labore possimus minus tenetur quidem qui laboriosam.
        Tenetur illum doloremque hic laudantium aperiam veniam mollitia officia eaque animi porro sequi eligendi maiores sint sit, ullam ea. Perferendis quisquam odio vel, nulla magnam autem illum animi omnis accusamus.
        Ad hic quam dolorum cumque excepturi temporibus ea voluptate aliquid quaerat eaque perspiciatis pariatur expedita sed, recusandae ipsa a! Et nulla pariatur odio omnis maxime quibusdam dolore dignissimos expedita sequi.
        Dolorem eos aspernatur sunt, reiciendis a modi ea? Alias voluptatum impedit asperiores facere animi, perferendis ab, officia quia eum eius in quibusdam, cumque obcaecati vitae corporis. Magni voluptas eveniet iure.
        Dolore quis voluptate saepe. Eius a, odit quisquam nobis neque ipsa, culpa vero corrupti eum vitae accusamus magnam repudiandae tempora eos id consequatur. Quas animi voluptas similique, dolor vel excepturi?
        Quas neque atque ut, illum aut officia, numquam eum voluptatum magnam distinctio provident! Iure veritatis quo accusantium autem enim libero accusamus cumque rerum dolor amet velit, quidem, ea earum facere.
        Iste mollitia ad enim minus quaerat placeat repudiandae omnis itaque, consectetur assumenda nam, nemo maiores suscipit ratione accusantium provident rerum quia. Deserunt, neque ullam? Maxime ut rerum quam doloremque totam?
        Distinctio reiciendis autem pariatur repudiandae hic, at, beatae voluptatem asperiores odit voluptate obcaecati alias eum blanditiis molestiae quas quos perferendis. Nemo tenetur, doloremque laboriosam fugiat adipisci cumque dolores eum atque.
        Dolor eligendi repellat quasi aliquam blanditiis omnis. Iste sapiente perspiciatis ratione aut nostrum hic impedit. Expedita dignissimos vero, quae perferendis quasi corporis sit quis amet suscipit, ex quas qui ad!
        Error omnis consectetur at perferendis ut accusantium a quis nemo cum enim atque velit voluptate quo repudiandae ea est eaque odio, consequuntur aspernatur nam, incidunt iure minima similique dolor. Explicabo.
        Rerum eveniet cumque nisi obcaecati et fugiat doloribus doloremque velit minima ipsum perferendis eum assumenda esse excepturi laboriosam, vero quia ut voluptas iusto voluptates corrupti. Nisi sapiente reiciendis perspiciatis maxime.
        Sed quo ducimus, blanditiis repellendus fuga laborum laboriosam. Porro ea dolorum ducimus facere quos laboriosam, illo nesciunt quaerat, mollitia excepturi doloremque praesentium iure id consequuntur veniam delectus! Molestiae, minima explicabo?
        Maiores quibusdam deleniti ducimus possimus earum soluta excepturi accusantium dicta? Modi corporis quam corrupti iusto. Amet fugit sed in eaque quam facilis aspernatur quasi aperiam, harum rem, a praesentium temporibus?
        Repellendus expedita fuga accusamus quod eius! Impedit vel nesciunt fuga explicabo recusandae, laboriosam pariatur aspernatur doloribus similique tempore incidunt animi ut quo, consequuntur labore nisi saepe iste qui. Inventore, dolor.
        Vitae aliquam repellat consequatur adipisci commodi aliquid veritatis laudantium. Impedit ab odit totam doloremque nulla, cupiditate unde reprehenderit non. Placeat reiciendis cum commodi laborum quam, saepe atque dolore itaque nobis.
        Vero corrupti facilis, sed consectetur enim officia asperiores aliquam magni similique quod laborum, accusamus eaque repudiandae omnis, veniam vitae animi labore corporis doloribus quaerat perspiciatis nobis saepe optio excepturi! Voluptates?
        Ea corporis dignissimos possimus temporibus quia ratione expedita quis optio mollitia eum ipsam animi illo error enim dolore quaerat architecto explicabo, nisi sunt consectetur. Optio reprehenderit ad pariatur saepe dolorum!
        Eligendi cumque iusto eius, eum, dicta omnis unde sequi vero optio, fugiat molestias sapiente consequatur distinctio illo! Esse nostrum sunt, at repellat suscipit delectus dolorem, ab provident consectetur nemo hic!
        At cumque dolore esse maxime vel earum quibusdam animi quo suscipit. Eius nisi in fuga vero, itaque natus autem rem asperiores ut repudiandae earum magni, porro aut a explicabo veritatis?
        Explicabo quam alias dolores inventore, unde, in excepturi vero nesciunt recusandae sint enim ipsam eius cupiditate, cum assumenda veniam ipsum vel ea laudantium aut sapiente expedita. Minus distinctio suscipit ducimus.
        Sint, illo! Doloremque earum aspernatur assumenda voluptatibus. Accusamus, nulla debitis ad voluptatem tenetur laborum dignissimos molestias in delectus, doloremque quia deleniti nesciunt et aut aliquid aperiam repellat animi quo reprehenderit.
        Provident rem voluptatum repellendus doloribus explicabo animi vitae, voluptates placeat alias aspernatur quis eum omnis eius, temporibus autem nulla. Eum, quas sequi voluptatibus a nobis maiores ad inventore possimus totam!
        Assumenda animi blanditiis, corrupti fuga explicabo possimus vitae exercitationem, vero ducimus omnis nihil, laboriosam cupiditate ipsam facilis non ex voluptatem neque aperiam inventore dolores optio laborum! Atque ad provident saepe.
        Ducimus dicta aperiam quod fuga sed enim commodi blanditiis earum, quos necessitatibus doloremque sit omnis quis, alias suscipit inventore voluptate ad. Soluta voluptatibus consequuntur est optio, nam sint quam placeat?
        Fugiat quia harum itaque nemo adipisci numquam odit delectus tempora! Itaque facere adipisci sit debitis magnam repellendus doloremque aspernatur totam magni! Perferendis omnis impedit blanditiis repellendus accusantium expedita quia rem?
        Hic odit, vitae repellat cum consectetur officia ipsa excepturi sit vero facilis praesentium itaque asperiores minus velit minima aut. In aspernatur eligendi architecto cumque fuga itaque facilis, natus atque tenetur!
        Quasi veritatis tempore sint perferendis odit, aliquam officiis qui quos minus ipsa eaque nemo ea enim? Iure aliquam modi sunt expedita dolorem, molestiae amet inventore, natus aperiam possimus ea nobis?
        Illum sint eligendi soluta itaque impedit sequi repudiandae, doloribus quibusdam exercitationem delectus assumenda nihil vel aliquam possimus ullam perferendis nostrum quos inventore dolorem. Dolores quas temporibus consectetur ipsam unde explicabo.
        Laboriosam suscipit omnis repudiandae blanditiis doloremque consequuntur modi atque assumenda praesentium ipsa! Quasi, molestias libero atque recusandae architecto distinctio labore molestiae porro! Ex aspernatur ipsam consequuntur veritatis laboriosam nesciunt dicta.
        Voluptatibus accusantium reiciendis officia adipisci dolorum dolore, cum voluptatum, hic unde cumque nam voluptatem pariatur ullam excepturi? Incidunt esse, exercitationem porro molestiae unde repellendus, repudiandae neque iure assumenda, necessitatibus blanditiis.
        Ex velit voluptatem, asperiores adipisci facere eum excepturi eveniet hic optio aperiam quae iure eius ut molestias? Expedita magni praesentium temporibus hic eos iure dolorem consectetur nostrum fugiat? Officia, quas!
        Obcaecati deleniti quisquam aperiam, architecto totam possimus doloribus. Ipsam voluptatem dolorum quam id atque aut nulla voluptate ut, qui dolores, amet placeat facere exercitationem numquam consequuntur quae hic accusantium explicabo!
        Corporis inventore asperiores aut, sit veritatis reiciendis suscipit dolorum incidunt autem facilis necessitatibus non error nihil placeat quia est cupiditate nisi porro. Saepe asperiores debitis, cum magni alias itaque doloremque.
        Incidunt iusto excepturi assumenda est delectus ullam nobis, similique tempore iure illum. Enim quaerat tenetur aliquid molestiae, fugit illo quis dolore praesentium repellat amet. Similique error quas dolorum esse id!
        Officia illo velit similique? Harum esse accusantium dolorem molestias minus reiciendis animi, rem blanditiis suscipit consequuntur nulla ducimus veritatis eveniet maiores iusto in quia distinctio corporis facilis at eaque deleniti.
        Repellendus quod id ipsa est et provident nulla reprehenderit voluptatum porro a assumenda necessitatibus nam, voluptates consequatur tenetur qui fugit modi excepturi iste ducimus sint debitis? Reiciendis ad laboriosam vitae.
        Sequi quis quas repellendus molestias velit illo dolorum odit aut, corrupti ex corporis tenetur saepe laudantium neque, laboriosam tempore est rem voluptatibus sit recusandae at! Nisi nam impedit quos ut!
        Magni, dolor ullam neque doloribus dignissimos consequuntur, cumque possimus dolorem corrupti, saepe voluptate deleniti quasi assumenda architecto ad. Ipsum libero tenetur odio, nulla laudantium dolorem omnis dicta quia iure soluta?
        Blanditiis laboriosam possimus fugit rem tempore. Fuga error, in accusamus nobis ipsam facilis! Distinctio beatae, alias quidem corporis debitis, iste ex non, magni nulla sunt velit reprehenderit quis facilis unde.
        Quos rerum facere alias non culpa sed voluptate facilis, quisquam eius maiores laboriosam dolores maxime reprehenderit ullam velit impedit beatae iure repudiandae dicta quidem qui! Reiciendis laboriosam iure in maiores.
        Quos, asperiores quod? Provident, modi officiis deleniti officia aspernatur ratione impedit fuga sit! Eos sunt aliquid neque alias animi esse libero? Repellendus temporibus labore facilis perferendis exercitationem quo id illum!
        Illum impedit nam quaerat! Officiis, molestiae dolor, porro numquam dicta soluta fuga cum delectus temporibus esse nobis suscipit, accusamus asperiores. Enim repellendus ratione quae tempora expedita cupiditate, eligendi quaerat debitis?
        Amet ab culpa velit pariatur earum, eaque voluptatum quidem nesciunt dolores excepturi? Non enim, ipsa reiciendis quasi omnis facilis! Porro fugiat numquam sed debitis vitae aliquid eveniet explicabo, non nisi!
        Veniam perferendis ea in blanditiis ipsa illum iure sunt sint laborum quibusdam qui asperiores delectus quas minima tempora accusamus, non fuga, nemo ipsum. Harum minima praesentium consequuntur labore ducimus optio?
        Nihil, minus modi! Distinctio ducimus suscipit unde quaerat. Explicabo quod, molestias quae, animi totam sapiente autem quos veniam numquam accusantium quis ab quia at inventore consequuntur tenetur ratione quidem nisi?
        Quasi quaerat reprehenderit quam accusantium error officiis assumenda esse non repellendus doloremque repellat nisi asperiores cumque sunt dolor, ullam omnis. Est assumenda enim culpa dolor maxime repudiandae labore hic recusandae!
        Neque sit atque eveniet ipsam consequatur numquam sint labore dolore hic tempora, commodi, odio eos quos. Eveniet quam voluptatem dicta maxime laboriosam quis perspiciatis consequatur. Error tenetur nostrum impedit placeat!
        Est dolorum dolore esse temporibus voluptatum consectetur enim voluptatem tempora nostrum sit, assumenda autem earum iusto! Quam, doloremque dolorem eum eius odit totam deserunt quas, tempore consequatur laborum commodi error?
        Molestiae ipsa autem dolores blanditiis, similique dicta dolorem fugiat tempora distinctio doloremque amet rem reprehenderit eum! Voluptatum facere voluptatem aliquid autem nam id, eaque necessitatibus, ullam veniam at, quo excepturi.
        Deleniti voluptatibus sit quia ipsa mollitia saepe ducimus facilis ullam alias quaerat, voluptatem eaque odit quasi repudiandae temporibus quibusdam neque cupiditate culpa. Quis est expedita itaque repellendus eveniet, quia ab.
        Reprehenderit, mollitia. Alias quae rerum unde soluta rem porro, sint quis quisquam quod dolorum! Excepturi alias ab provident quam aliquam ex, illum totam, exercitationem quis architecto est iusto aliquid sed?
        Perspiciatis ex tempora sint fugiat obcaecati soluta eos at! A assumenda quidem doloribus excepturi corporis doloremque enim itaque, iste explicabo tenetur voluptatem quasi nemo totam neque sunt nobis quaerat fugit?
        At officiis quos quasi necessitatibus voluptatibus, ut beatae quam molestiae modi asperiores tempore facilis dicta exercitationem numquam deleniti deserunt ullam illum? Totam repellat deleniti esse excepturi quaerat tempora aspernatur officiis.
        Eos dolorum eaque ex nemo culpa. Eos perferendis qui odit libero earum veritatis ducimus itaque fugit officiis et, excepturi dolore nobis suscipit enim sint neque illo maiores expedita saepe iure.
        Voluptatem atque fugiat alias nam enim repudiandae cum eveniet temporibus nostrum omnis facere, asperiores quas deleniti quos nulla illo repellat aut aspernatur distinctio quibusdam a hic qui autem ut! Assumenda?
        Nobis debitis fugit cumque eligendi tenetur? At earum, deleniti doloribus, cupiditate saepe consectetur autem blanditiis, ullam sint cumque doloremque in harum rem omnis porro tempora commodi iste ea nihil reiciendis.
        Maxime obcaecati quibusdam pariatur, vitae eligendi dolores architecto explicabo numquam deleniti repellat eum amet nam modi nisi ipsa beatae suscipit et voluptatibus ad ea, eos, inventore culpa voluptas. Quas, quam.
      </Stack>
    </ShellLayout>
  )
}

export default Home
